# Generated by Django 6.0.2 on 2026-03-03 11:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                (
                    "representant",
                    models.CharField(
                        help_text="Nom du signataire côté entreprise", max_length=150
                    ),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant Commun de l'Entreprise",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ETUDIANT", "Étudiant Master"),
                            ("ENSEIGNANT", "Enseignant Encadrant"),
                            ("COORDINATEUR", "Coordinateur de Filière"),
                            ("VICE_DOYEN", "Vice-Doyen"),
                        ],
                        default="ETUDIANT",
                        max_length=20,
                    ),
                ),
                ("filiere", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet_stage", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "statut",
                    models.IntegerField(
                        choices=[
                            (0, "Initié (Formulaire rempli)"),
                            (1, "En attente d'encadrement"),
                            (2, "En attente de coordination"),
                            (3, "En attente du décanat"),
                            (4, "Validé (Signé par le Vice-Doyen)"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "document_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="conventions_pdfs/"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "enseignant",
                    models.ForeignKey(
                        limit_choices_to={"role": "ENSEIGNANT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conventions_encadrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        limit_choices_to={"role": "ETUDIANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions_etudiant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.entreprise",
                    ),
                ),
            ],
        ),
    ]
