# Generated by Django 6.0.2 on 2026-05-12 10:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.TextField()),
                (
                    "representant",
                    models.CharField(
                        help_text="Nom du signataire côté entreprise", max_length=150
                    ),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant Commun de l'Entreprise",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormationDoctorale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Titre de la formation",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cible_1ere_annee",
                    models.BooleanField(default=True, verbose_name="1ère Année"),
                ),
                (
                    "cible_2eme_annee",
                    models.BooleanField(default=False, verbose_name="2ème Année"),
                ),
                (
                    "cible_3eme_annee",
                    models.BooleanField(default=False, verbose_name="3ème Année"),
                ),
                (
                    "cible_4eme_annee_plus",
                    models.BooleanField(default=False, verbose_name="4ème année et +"),
                ),
                ("obligatoire", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Formation Doctorale (Catalogue)",
                "verbose_name_plural": "Formations Doctorales",
            },
        ),
        migrations.CreateModel(
            name="TypeMobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Type de Mobilité"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Type de Mobilité",
                "verbose_name_plural": "Types de Mobilité",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ETUDIANT", "Étudiant"),
                            ("ENSEIGNANT", "Enseignant"),
                            ("COORDINATEUR", "Coordinateur"),
                            ("ADMINISTRATEUR", "Administrateur"),
                            ("VICE_DOYEN", "Vice-Doyen"),
                            ("DOCTORANT", "Doctorant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EnseignantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("specialite", models.CharField(blank=True, max_length=150, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseignant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "coordinateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filieres_gerees",
                        to="conventions.enseignantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet_stage", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "statut",
                    models.IntegerField(
                        choices=[
                            (0, "Initié (Formulaire rempli)"),
                            (1, "En attente d'encadrement"),
                            (2, "En attente de coordination"),
                            (3, "En attente du décanat"),
                            (4, "Validé (Signé par le Vice-Doyen)"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "document_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="conventions_pdfs/"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                ("qr_x", models.FloatField(blank=True, null=True)),
                ("qr_y", models.FloatField(blank=True, null=True)),
                ("qr_page", models.IntegerField(blank=True, null=True)),
                (
                    "motif_rejet",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif du refus"
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conventions_encadrees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encadrant (Optionnel)",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        limit_choices_to={"role": "ETUDIANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions_etudiant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.entreprise",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conventions.filiere",
                        verbose_name="Filière",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("etablissement_accueil", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "type_mobilite",
                    models.CharField(
                        choices=[
                            ("STAGE", "Stage de recherche"),
                            ("COURS", "Semestre d'études"),
                            ("CONFERENCE", "Participation Conférence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="mobilites/justificatifs/",
                        verbose_name="Attestation / Rapport (PDF)",
                    ),
                ),
                (
                    "etat",
                    models.BooleanField(
                        default=False, verbose_name="Dossier traité / clôturé"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobilites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("lien", models.CharField(blank=True, max_length=255, null=True)),
                ("est_lue", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_universitaire",
                    models.CharField(
                        help_text="Exemple: 2024/2025",
                        max_length=9,
                        verbose_name="Année universitaire",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "formateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_animees",
                        to="conventions.enseignantprofile",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="conventions.formationdoctorale",
                        verbose_name="Formation liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de Formation",
                "verbose_name_plural": "Sessions de Formation",
                "unique_together": {("formation", "annee_universitaire")},
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinateur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "PAI",
                    models.CharField(
                        blank=True,
                        help_text="Exemple : 2024",
                        max_length=4,
                        null=True,
                        verbose_name="Première Année d'Inscription (PAI)",
                    ),
                ),
                (
                    "CNE",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CNE"
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conventions.filiere",
                        verbose_name="Filière / Master",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConventionMobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laboratoire_accueil", models.CharField(max_length=255)),
                ("ville_pays", models.CharField(max_length=200)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("contrat_signe", models.FileField(upload_to="mobilites/contrats/")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "retour_valide",
                    models.BooleanField(
                        default=False, verbose_name="Retour validé par l'admin"
                    ),
                ),
                (
                    "est_archive",
                    models.BooleanField(default=False, verbose_name="Dossier Archivé"),
                ),
                (
                    "doctorant",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTORANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobilites_doctorales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type_convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="conventions.typemobilite",
                        verbose_name="Type de Convention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipationFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "presence",
                    models.BooleanField(default=False, verbose_name="Présent / Validé"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscrits",
                        to="conventions.sessionformation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="conventions.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
                "unique_together": {("student", "session")},
            },
        ),
        migrations.CreateModel(
            name="InscriptionDoctorat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee_universitaire", models.CharField(max_length=10)),
                ("numero_reinscription", models.IntegerField(default=1)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                ("est_valide", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user__role": "DOCTORANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "annee_universitaire")},
            },
        ),
    ]
