# Generated by Django 6.0.2 on 2026-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formationdoctorale",
            name="credits",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de Crédits (ECTS)"
            ),
        ),
        migrations.AddField(
            model_name="formationdoctorale",
            name="volume_horaire",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Volume Horaire (VH) en heures"
            ),
        ),
    ]
