# Generated by Django 6.0.2 on 2026-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ETUDIANT", "Étudiant"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("COORDINATEUR", "Coordinateur"),
                    ("ADMINISTRATEUR", "Administrateur"),
                    ("VICE_DOYEN", "Vice-Doyen"),
                ],
                max_length=20,
            ),
        ),
    ]
