# Generated by Django 6.0.2 on 2026-03-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="qr_page",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="qr_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="qr_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
