# Generated by Django 6.0.2 on 2026-03-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0004_convention_qr_page_convention_qr_x_convention_qr_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="motif_rejet",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motif du refus"
            ),
        ),
    ]
