# Generated by Django 6.0.2 on 2026-04-20 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0005_convention_motif_rejet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conventions_encadrees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Encadrant (Optionnel)",
            ),
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la filière / Master"
                    ),
                ),
                (
                    "coordinateur",
                    models.ForeignKey(
                        limit_choices_to={"role": "COORDINATEUR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filieres_coordonnees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="convention",
            name="filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conventions.filiere",
                verbose_name="Filière",
            ),
        ),
    ]
