# Generated by Django 6.0.2 on 2026-04-20 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0006_alter_convention_enseignant_filiere_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobiliteDoctorat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laboratoire_accueil", models.CharField(max_length=255)),
                ("pays_destination", models.CharField(max_length=100)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("contrat_signe", models.FileField(upload_to="mobilites/contrats/")),
                (
                    "attestation_reception",
                    models.FileField(
                        blank=True, null=True, upload_to="mobilites/receptions/"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "doctorant",
                    models.ForeignKey(
                        limit_choices_to={"role": "ETUDIANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
