# Generated by Django 6.0.2 on 2026-04-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0007_mobilitedoctorat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilitedoctorat",
            name="doctorant",
        ),
        migrations.RemoveField(
            model_name="mobilitedoctorat",
            name="laboratoire_accueil",
        ),
        migrations.RemoveField(
            model_name="mobilitedoctorat",
            name="pays_destination",
        ),
        migrations.AddField(
            model_name="mobilitedoctorat",
            name="convention",
            field=models.OneToOneField(
                default=2026,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobilite",
                to="conventions.convention",
                verbose_name="Convention associée",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mobilitedoctorat",
            name="attestation_reception",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="mobilites/receptions/",
                verbose_name="Attestation de réception",
            ),
        ),
        migrations.AlterField(
            model_name="mobilitedoctorat",
            name="contrat_signe",
            field=models.FileField(
                upload_to="mobilites/contrats/",
                verbose_name="Contrat de mobilité (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="mobilitedoctorat",
            name="date_debut",
            field=models.DateField(verbose_name="Date de début de mobilité"),
        ),
        migrations.AlterField(
            model_name="mobilitedoctorat",
            name="date_fin",
            field=models.DateField(verbose_name="Date de fin de mobilité"),
        ),
    ]
