# Generated by Django 6.0.2 on 2026-04-20 10:30

import conventions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0008_remove_mobilitedoctorat_doctorant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConventionMobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee_premiere_inscription",
                    models.IntegerField(
                        default=conventions.models.annee_actuelle,
                        verbose_name="Année de 1ère inscription en Doctorat",
                    ),
                ),
                (
                    "laboratoire_accueil",
                    models.CharField(
                        max_length=255,
                        verbose_name="Laboratoire ou Établissement d'accueil",
                    ),
                ),
                (
                    "ville_pays",
                    models.CharField(
                        max_length=200, verbose_name="Ville et Pays de destination"
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(verbose_name="Date de début de mobilité"),
                ),
                ("date_fin", models.DateField(verbose_name="Date de fin de mobilité")),
                (
                    "contrat_signe",
                    models.FileField(
                        upload_to="mobilites/contrats/",
                        verbose_name="Contrat de mobilité (Signé par le labo d'accueil)",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "doctorant",
                    models.ForeignKey(
                        limit_choices_to={"role": "ETUDIANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobilites_doctorales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention de Mobilité",
                "verbose_name_plural": "Conventions de Mobilité",
            },
        ),
        migrations.DeleteModel(
            name="MobiliteDoctorat",
        ),
    ]
