# Generated by Django 6.0.2 on 2026-04-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0009_conventionmobilite_delete_mobilitedoctorat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeMobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Type de Mobilité"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Type de Mobilité",
                "verbose_name_plural": "Types de Mobilité",
            },
        ),
        migrations.AlterModelOptions(
            name="conventionmobilite",
            options={},
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="annee_premiere_inscription",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="contrat_signe",
            field=models.FileField(upload_to="mobilites/contrats/"),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="date_debut",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="date_fin",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="doctorant",
            field=models.ForeignKey(
                limit_choices_to={"role": "DOCTORANT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobilites_doctorales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="laboratoire_accueil",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="conventionmobilite",
            name="ville_pays",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ETUDIANT", "Étudiant"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("COORDINATEUR", "Coordinateur"),
                    ("ADMINISTRATEUR", "Administrateur"),
                    ("VICE_DOYEN", "Vice-Doyen"),
                    ("DOCTORANT", "Doctorant"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conventionmobilite",
            name="type_convention",
            field=models.ForeignKey(
                default=2026,
                on_delete=django.db.models.deletion.PROTECT,
                to="conventions.typemobilite",
                verbose_name="Type de Convention",
            ),
            preserve_default=False,
        ),
    ]
