# Generated by Django 6.0.2 on 2026-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0010_typemobilite_alter_conventionmobilite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionmobilite",
            name="retour_valide",
            field=models.BooleanField(
                default=False, verbose_name="Retour validé par l'admin"
            ),
        ),
    ]
