# Generated by Django 6.0.2 on 2026-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0011_conventionmobilite_retour_valide"),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionmobilite",
            name="est_archive",
            field=models.BooleanField(default=False, verbose_name="Dossier Archivé"),
        ),
    ]
