# Generated by Django 6.0.2 on 2026-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0012_conventionmobilite_est_archive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conventionmobilite",
            name="annee_premiere_inscription",
        ),
        migrations.AddField(
            model_name="customuser",
            name="PAI",
            field=models.IntegerField(default=2026),
        ),
    ]
