# Generated by Django 6.0.2 on 2026-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0013_remove_conventionmobilite_annee_premiere_inscription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="PAI",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
