# Generated by Django 6.0.2 on 2026-04-22 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0014_alter_customuser_pai"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "annee_doctorat_cible",
                    models.IntegerField(
                        choices=[
                            (1, "1ère Année"),
                            (2, "2ème Année"),
                            (3, "3ème Année"),
                            (4, "4ème+"),
                        ],
                        default=1,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_etudiant",
                    models.CharField(
                        choices=[
                            ("LICENCE", "Licence"),
                            ("MASTER", "Master"),
                            ("DOCTORANT", "Doctorant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filiere", models.CharField(max_length=255)),
                (
                    "structure_recherche",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "coordinateur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipationFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("presence", models.BooleanField(default=True)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.formation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscriptionDoctorat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee_universitaire", models.CharField(max_length=10)),
                ("numero_reinscription", models.IntegerField(default=1)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                ("est_valide", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"type_etudiant": "DOCTORANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "annee_universitaire")},
            },
        ),
    ]
