# Generated by Django 6.0.2 on 2026-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0015_formation_studentprofile_participationformation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="PAI",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="filiere",
        ),
    ]
