# Generated by Django 6.0.2 on 2026-04-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0016_remove_customuser_pai_remove_customuser_filiere"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("etablissement_accueil", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "annee_au_depart",
                    models.IntegerField(
                        help_text="Année de doctorat/master lors de la mobilité"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STAGE", "Stage de recherche"),
                            ("COURS", "Semestre d'études"),
                            ("CONFERENCE", "Participation Conférence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "etudiant_profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobilites",
                        to="conventions.studentprofile",
                    ),
                ),
            ],
        ),
    ]
