# Generated by Django 6.0.2 on 2026-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0017_mobilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilite",
            name="etat",
            field=models.BooleanField(
                default=False, verbose_name="Dossier traité / clôturé"
            ),
        ),
    ]
