# Generated by Django 6.0.2 on 2026-04-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0018_mobilite_etat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="structure_recherche",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="type_etudiant",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="filiere",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
