# Generated by Django 6.0.2 on 2026-04-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0019_remove_studentprofile_structure_recherche_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptiondoctorat",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user__role": "DOCTORANT"},
                on_delete=django.db.models.deletion.CASCADE,
                to="conventions.studentprofile",
            ),
        ),
    ]
