# Generated by Django 6.0.2 on 2026-04-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0020_alter_inscriptiondoctorat_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilite",
            old_name="type",
            new_name="type_mobilite",
        ),
        migrations.RemoveField(
            model_name="mobilite",
            name="etudiant_profil",
        ),
        migrations.AddField(
            model_name="mobilite",
            name="document_justificatif",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="mobilites/justificatifs/",
                verbose_name="Attestation / Rapport (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="mobilite",
            name="etudiant",
            field=models.ForeignKey(
                default=2005,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mobilites",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
