# Generated by Django 6.0.2 on 2026-04-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0021_rename_type_mobilite_type_mobilite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilite",
            name="annee_au_depart",
        ),
    ]
