# Generated by Django 6.0.2 on 2026-04-27 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0022_remove_mobilite_annee_au_depart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiere",
            name="nom",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="EnseignantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("specialite", models.CharField(blank=True, max_length=150, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseignant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formation",
            name="formateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formations_animees",
                to="conventions.enseignantprofile",
            ),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="coordinateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filieres_gerees",
                to="conventions.enseignantprofile",
            ),
        ),
    ]
