# Generated by Django 6.0.2 on 2026-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0023_alter_filiere_nom_enseignantprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formation",
            name="annee_doctorat_cible",
        ),
        migrations.AddField(
            model_name="formation",
            name="cible_1ere_annee",
            field=models.BooleanField(default=True, verbose_name="1ère Année"),
        ),
        migrations.AddField(
            model_name="formation",
            name="cible_2eme_annee",
            field=models.BooleanField(default=False, verbose_name="2ème Année"),
        ),
        migrations.AddField(
            model_name="formation",
            name="cible_3eme_annee",
            field=models.BooleanField(default=False, verbose_name="3ème Année"),
        ),
        migrations.AddField(
            model_name="formation",
            name="cible_4eme_annee_plus",
            field=models.BooleanField(default=False, verbose_name="4ème année et +"),
        ),
    ]
