# Generated by Django 6.0.2 on 2026-04-27 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0024_remove_formation_annee_doctorat_cible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationformation",
            name="note",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="participationformation",
            name="presence",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="participationformation",
            unique_together={("student", "formation")},
        ),
    ]
