# Generated by Django 6.0.2 on 2026-04-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0025_alter_participationformation_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conventions.filiere",
                verbose_name="Filière / Master",
            ),
        ),
    ]
